spring:
  config:
    import: optional:application-local.yaml

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StorageManager;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 8081